const Appliances = require('./appliances');
Appliances.blender.name = 'Blendy';
Appliances.blender.shout();
console.log(Appliances.blender.attack());
Appliances.microwave.name = 'The Nuke';
Appliances.microwave.shout();
console.log(Appliances.microwave.attack());
const Computers = require('./computers');
Computers.mac.name = 'Steve Jobs';
Computers.mac.shout();
console.log(Computers.mac.attack());
Computers.windows.name = 'Bill Gates';
Computers.windows.shout();
console.log(Computers.windows.attack());
const Powertools = require('./powertools');
Powertools.drill.name = 'Drillson';
Powertools.drill.shout();
console.log(Powertools.drill.attack());
Powertools.jigsaw.name = 'Jiggy';
Powertools.jigsaw.shout();
console.log(Powertools.jigsaw.attack());
